Svelte hooks
ItemConsulting/mattilsynet-web pull request #10
Opened 2021-08-06 07:59 UTC by lha047

- handle() to handle .env variables
- getSession() to get values from cookies

2021-08-11 10:01 UTC, tajakobsen requested changes
Good job! Just a few small things to look at.

2021-08-11 10:01 UTC, tajakobsen commented on src/lib/utils/cookieUtils.ts
> +    }, {})
```suggestion
    const form = pageCookies.reduce((acc, p) => {
      const [key, value] = p.split(':')
      return {
        ...acc,
        [key]: mapInputToObject(value),
      }
    }, {})
```

2021-08-12 08:29 UTC, lha047 commented on src/lib/utils/cookieUtils.ts
> +    maxAge: COOKIE_MAX_AGE,
If we remove it will be a session cookie as you describe. Ill do the update

2021-08-12 09:40 UTC, tajakobsen requested changes
I think everything looks good now! :+1:

I just have one more small suggestion – take it or leave it – before I merge.

2021-08-12 09:40 UTC, tajakobsen commented on src/lib/utils/cookieUtils.ts
> +  return {}
I think it looks good! But here is a suggestion of a slightly more FP way to do it. Is it simpler or not?

```suggestion
  return (cookies[COOKIE_NAME] ?? '')
    .split('|')
    .filter((cookie) => cookie.length > 0)
    .reduce((acc, p) => {
      const [key, value] = p.split(':')
      
      return {
        ...acc,
        [key]: mapInputToObject(value),
      }
    }, {})
```

2021-08-12 09:50 UTC, tajakobsen approved these changes
Great job! Closing and merging to main.

2021-08-12 09:51 UTC, merged