Components
ItemConsulting/mattilsynet-web pull request #3
Opened 2021-08-02 14:09 UTC by lha047

Add components for page elements

2021-08-03 09:07 UTC, tajakobsen requested changes
Very good job! But there are a few things that I think should be looked at.

Note that some of the comments are very opinionated by me. So don't be afraid to challenge them if you disagree. And we'll decide on a common standard to write the code together.

Some of the main things that needs to be addressed are:
 1. I think some of the wrapping components are redundant
 2. Some components use ids that are not necessarily unique
 3. The components encapsulating input fields might be made more independent of functionality related to multipageform

Also see if it's possible to run prettier on the code.

2021-08-03 09:47 UTC, lha047 commented on src/lib/mapper/mapper.ts
> +    fieldName: findFieldNameForError(error),
Will update :)

2021-08-03 09:49 UTC, lha047 commented on src/components/input/TextInput.svelte
> +  id={name}
Will make a task to add unique ids for the components we decide to keep

2021-08-03 09:55 UTC, lha047 commented on src/components/form/FormErrorSummary.svelte
> +{#if errors}
Will update check

2021-08-03 10:52 UTC, lha047 commented on src/components/form/InputErrorMessage.svelte
> +    <span class="inclusively-hidden">Feilmelding:</span>
Agree :)

2021-08-03 11:18 UTC, lha047 commented on src/lib/mapper/mapper.ts
> +};
Just used to writing functions this way (from functions in React-components) 😂 
Will update :)

2021-08-03 11:47 UTC, lha047 commented on src/lib/mapper/mapper.ts
> +  return errors?.find(({ fieldName }) => fieldName === props.name);
Willl fix

2021-08-03 12:11 UTC, lha047 commented on src/components/form/InputErrorMessage.svelte
> +  export let error: UIError;
Error passed down a few levels. My thought was to group the fields in an object would make it more consistent and less to pass down

2021-08-03 12:19 UTC, lha047 commented on src/components/input/RadioGroup.svelte
> +    <div class="radio-item">
It was for styling. Woud you prefere to wrap the input with the label?

2021-08-04 13:12 UTC, tajakobsen requested changes
Good job! There are mainly code standard suggestions here now. Should be quick to fix.

2021-08-04 13:12 UTC, tajakobsen commented on src/components/input/RadioGroup.svelte
> +        value={radio.name}
There should probably be a `radio.value` from XP too? Or is this enough?

2021-08-04 13:12 UTC, tajakobsen commented on src/components/input/RadioGroup.svelte
> +    <label class="form-label" for={radio.name}>
Stack the attributes.

2021-08-04 13:12 UTC, tajakobsen commented on src/components/input/TextArea.svelte
> +<label class="form-label" for={name}>
Stack attributes

2021-08-04 13:12 UTC, tajakobsen commented on src/components/input/TextArea.svelte
> +  export let disclosure;
We don't need `disclosure` any more right?

2021-08-04 13:12 UTC, tajakobsen commented on src/components/input/TextArea.svelte
> +  export let value = undefined;
We probably don't need to initialize variables to `undefined`

2021-08-04 13:12 UTC, tajakobsen commented on src/components/input/TextArea.svelte
> +<textarea id={name} {name} bind:value aria-describedby={`${name}-hint ${name}-error`} aria-invalid={!!error.message} />
Stack attributes vertifally

2021-08-04 13:12 UTC, tajakobsen commented on src/components/input/TextInput.svelte
> +  export let disclosure;
`disclosure` is not in use

2021-08-04 13:12 UTC, tajakobsen commented on src/components/input/TextInput.svelte
> +  export let value = undefined;
Do we need to default to `undefined`?

2021-08-04 13:12 UTC, tajakobsen commented on src/components/input/TextInput.svelte
> +<label class="form-label" for={name}>
Stack attributes

2021-08-04 13:12 UTC, tajakobsen commented on src/components/input/TextInput.svelte
> +/>
Move `/>` to line above

2021-08-04 13:12 UTC, tajakobsen commented on src/components/input/TextInput.test.ts
> +  let disclosure;
Is `disclosure` used in the components anymore?

2021-08-05 07:36 UTC, lha047 commented on src/components/form/FormErrorSummary.svelte
> +  <div class="error-summary" role="alert" tabindex="-1" aria-labelledby="error-summary-heading">
Automatic format

2021-08-05 10:44 UTC, tajakobsen approved these changes
Very good job! Closing and merging to *main*.

2021-08-05 10:46 UTC, merged